tesseract 4.png stdout -l eng >> test1.txt
tesseract 5.png stdout -l eng >> test1.txt
tesseract 6.png stdout -l eng >> test1.txt
tesseract 7.png stdout -l eng >> test1.txt
tesseract 8.png stdout -l eng >> test1.txt
tesseract 9.png stdout -l eng >> test1.txt
tesseract 10.png stdout -l eng >> test1.txt
tesseract 11.png stdout -l eng >> test1.txt
tesseract 12.png stdout -l eng >> test1.txt