for ($i = 1; $i -le 32; $i++) {
   tesseract "$i.png" stdout -l eng | Out-File -FilePath test1.txt -Append
}
tesseract 38.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 44.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 50.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 56.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 62.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 65.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 70.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 71.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 77.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 83.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 89.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 95.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 98.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 101.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 105.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 109.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 115.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 121.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 126.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 131.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 134.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 135.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 138.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 139.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 141.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 143.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 145.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 147.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 148.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 149.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 150.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 151.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 152.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 153.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 155.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 156.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 158.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 159.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 160.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 161.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 164.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 165.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 167.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 168.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 170.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 172.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 174.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 176.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 179.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 181.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 184.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 186.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 189.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 191.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 194.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 196.png stdout -l eng | Out-File -FilePath test1.txt -Append
tesseract 199.png stdout -l eng | Out-File -FilePath test1.txt -Append
